apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-api
spec:
  rules:
  - host: "hello.binaryflavor.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-api
            port:
              number: 3000
  ingressClassName: nginx
