server:
  replicas: 1
  extraArgs:
    - --insecure

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      acme.cert-manager.io/http01-edit-in-place: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: nginx
    hosts:
      - argo.binaryflavor.com
    paths:
      - /
    pathType: Prefix

    tls:
      - secretName: argocd-cert
        hosts:
          - argo.binaryflavor.com

repoServer:
  replicas: 1
