dashboard:
  # -- Deploy dashboard server
  enabled: true
  # -- Value of label `app.kubernetes.io/component`
  component: rollouts-dashboard
  # -- [Node selector]
  nodeSelector: {}
  # -- [Tolerations] for use with node taints
  tolerations: []
  # -- Assign custom [affinity] rules to the deployment
  affinity: {}
  # -- [priorityClassName] for the dashboard server
  priorityClassName: ""
  image:
    # -- Registry to use
    registry: quay.io
    # --  Repository to use
    repository: argoproj/kubectl-argo-rollouts
    # -- Overrides the image tag (default is the chart appVersion)
    tag: ""
    # -- Image pull policy
    pullPolicy: IfNotPresent
  # -- Additional command line arguments to pass to rollouts-dashboard. A list of flags.
  extraArgs: []
  # -- Resource limits and requests for the dashboard pods.
  resources: {}
  # -- Security Context to set on pod level
  podSecurityContext:
    runAsNonRoot: true
  # -- Security Context to set on container level
  containerSecurityContext: {}
  service:
    # -- Sets the type of the Service
    type: ClusterIP
    # -- LoadBalancer will get created with the IP specified in this field
    loadBalancerIP: ""
    # -- Source IP ranges to allow access to service from
    loadBalancerSourceRanges: []
    # -- Dashboard service external IPs
    externalIPs: []
    # -- Service annotations
    annotations: {}
    # -- Service labels
    labels: {}
    # -- Service port name
    portName: dashboard
    # -- Service port
    port: 3100
    # -- Service target port
    targetPort: 3100
    # -- (int) Service nodePort
    nodePort:
  serviceAccount:
    # -- Specifies whether a dashboard service account should be created
    create: true
    # -- Annotations to add to the dashboard service account
    annotations: {}
    # -- The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  ## Ingress configuration.
  ## ref: https://kubernetes.io/docs/user-guide/ingress/
  ##
  ingress:
    # -- Enable dashboard ingress support
    enabled: false
    # -- Dashboard ingress annotations
    annotations: {}
    # -- Dashboard ingress labels
    labels: {}
    # -- Dashboard ingress class name
    ingressClassName: ""

    # -- Dashboard ingress hosts
    ## Argo Rollouts Dashboard Ingress.
    ## Hostnames must be provided if Ingress is enabled.
    ## Secrets must be manually created in the namespace
    hosts: []
      # - argorollouts.example.com

    # -- Dashboard ingress paths
    paths:
      - /
    # -- Dashboard ingress path type
    pathType: Prefix
    # -- Dashboard ingress extra paths
    extraPaths: []
      # - path: /*
      #   backend:
      #     serviceName: ssl-redirect
      #     servicePort: use-annotation
      ## for Kubernetes >=1.19 (when "networking.k8s.io/v1" is used)
      # - path: /*
      #   pathType: Prefix
      #   backend:
      #     service
      #       name: ssl-redirect
      #       port:
      #         name: use-annotation

    # -- Dashboard ingress tls
    tls: []
      # - secretName: argorollouts-example-tls
      #   hosts:
      #     - argorollouts.example.com
